### ISSUE TITLE
Custom URL's with .json suffix doesn't returns the JSON response but text/html

### ISSUE THREAD

**Issue by alexandersch** [sulu/SuluHeadlessBundle#67] opened 2020-12-16 17:12 UTC
I've setup a custom URL pointing to an internal page. I would expect to get the JSON output when requesting `domain.com/custom.json`. But unfortunately I got the HTML response.

![image](https://user-images.githubusercontent.com/3180083/102382128-5b249580-3fca-11eb-8f5a-f6852f29fb39.png)

**Comment by niklasnatter** [comment] 2021-01-12 16:31
Hey,
what versions are you using? how have you configured your custom url? 

I cannot reproduce the problem using Sulu 2.1 with the master branch of this bundle and the following custom url:
![Screenshot 2021-01-12 at 17 29 30](https://user-images.githubusercontent.com/13310795/104343025-c1360700-54fb-11eb-9fd5-185b786b1c6c.png)

I sent the following request:
<img width="681" alt="Screenshot 2021-01-12 at 17 30 40" src="https://user-images.githubusercontent.com/13310795/104343184-ec205b00-54fb-11eb-98a3-c85161546a47.png">

**Comment by niklasnatter** [comment] 2021-01-14 08:39
I figured that this can be reproduced by enabling the `redirect` option and added some fixes for that in https://github.com/sulu/sulu/pull/5747 🙂

**Comment by niklasnatter** [comment] 2021-01-14 08:55
Should hopefully be fixed by https://github.com/sulu/sulu/pull/5747. Thanks for reporting!

**Closed by niklasnatter** 2021-01-14 08:55 UTC
